In [6]:
import numpy as np
np.random.seed(0)

A2 = np.random.random((4,4))

In [7]:
A2

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [9]:
A3 = A2[:2, :2]
A3

array([[0.5488135 , 0.71518937],
       [0.4236548 , 0.64589411]])

In [10]:
print(A3 * 2)

[[1.09762701 1.43037873]
 [0.8473096  1.29178823]]


In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a4 = np.arange(1,10).reshape((3,3))
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a5 = a4.reshape((9,1))
a5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.concatenate([a1, a2])
a3

array([1, 2, 3, 4, 5, 6])

In [31]:
a1,a2,a4 = np.split(a3,[2,4])
print(a1,a2,a4)

[1 2] [3 4] [5 6]


In [33]:
b1 = np.array([[1,2], [4,5]])
b1

array([[1, 2],
       [4, 5]])

In [34]:
b2 = [[3], [6]]
b2

[[3], [6]]

In [37]:
bb1 = np.append(b1, b2, axis=1)
bb1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
x = np.array([[1,3], [4,6]])
x

array([[1, 3],
       [4, 6]])

In [39]:
x1 = [2,5]
x1

[2, 5]

In [40]:
x2 = np.insert(x, 1, x1, axis=1)
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
print(y+1)

[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
r1 = np.random.random()
r1

0.02021839744032572

In [44]:
a1 = np.arange(1, 51) * r1
a1

array([0.0202184 , 0.04043679, 0.06065519, 0.08087359, 0.10109199,
       0.12131038, 0.14152878, 0.16174718, 0.18196558, 0.20218397,
       0.22240237, 0.24262077, 0.26283917, 0.28305756, 0.30327596,
       0.32349436, 0.34371276, 0.36393115, 0.38414955, 0.40436795,
       0.42458635, 0.44480474, 0.46502314, 0.48524154, 0.50545994,
       0.52567833, 0.54589673, 0.56611513, 0.58633353, 0.60655192,
       0.62677032, 0.64698872, 0.66720712, 0.68742551, 0.70764391,
       0.72786231, 0.74808071, 0.7682991 , 0.7885175 , 0.8087359 ,
       0.8289543 , 0.84917269, 0.86939109, 0.88960949, 0.90982788,
       0.93004628, 0.95026468, 0.97048308, 0.99070147, 1.01091987])

In [48]:
a2 = a1.reshape(10,5)
a2

array([[0.0202184 , 0.04043679, 0.06065519, 0.08087359, 0.10109199],
       [0.12131038, 0.14152878, 0.16174718, 0.18196558, 0.20218397],
       [0.22240237, 0.24262077, 0.26283917, 0.28305756, 0.30327596],
       [0.32349436, 0.34371276, 0.36393115, 0.38414955, 0.40436795],
       [0.42458635, 0.44480474, 0.46502314, 0.48524154, 0.50545994],
       [0.52567833, 0.54589673, 0.56611513, 0.58633353, 0.60655192],
       [0.62677032, 0.64698872, 0.66720712, 0.68742551, 0.70764391],
       [0.72786231, 0.74808071, 0.7682991 , 0.7885175 , 0.8087359 ],
       [0.8289543 , 0.84917269, 0.86939109, 0.88960949, 0.90982788],
       [0.93004628, 0.95026468, 0.97048308, 0.99070147, 1.01091987]])

In [49]:
a2.sum()

25.77845673641529

In [50]:
a2.sum(axis=0)

array([4.7513234 , 4.95350737, 5.15569135, 5.35787532, 5.5600593 ])

In [51]:
a2.sum(axis=1)

array([0.30327596, 0.8087359 , 1.31419583, 1.81965577, 2.32511571,
       2.83057564, 3.33603558, 3.84149551, 4.34695545, 4.85241539])

In [52]:
a2.mean()

0.5155691347283058

In [53]:
a2.mean(axis=1)

array([0.06065519, 0.16174718, 0.26283917, 0.36393115, 0.46502314,
       0.56611513, 0.66720712, 0.7682991 , 0.86939109, 0.97048308])

In [54]:
a2.mean(axis=0)

array([0.47513234, 0.49535074, 0.51556913, 0.53578753, 0.55600593])

In [59]:
print(a2)
a2.min(axis=1)

[[0.0202184  0.04043679 0.06065519 0.08087359 0.10109199]
 [0.12131038 0.14152878 0.16174718 0.18196558 0.20218397]
 [0.22240237 0.24262077 0.26283917 0.28305756 0.30327596]
 [0.32349436 0.34371276 0.36393115 0.38414955 0.40436795]
 [0.42458635 0.44480474 0.46502314 0.48524154 0.50545994]
 [0.52567833 0.54589673 0.56611513 0.58633353 0.60655192]
 [0.62677032 0.64698872 0.66720712 0.68742551 0.70764391]
 [0.72786231 0.74808071 0.7682991  0.7885175  0.8087359 ]
 [0.8289543  0.84917269 0.86939109 0.88960949 0.90982788]
 [0.93004628 0.95026468 0.97048308 0.99070147 1.01091987]]


array([0.0202184 , 0.12131038, 0.22240237, 0.32349436, 0.42458635,
       0.52567833, 0.62677032, 0.72786231, 0.8289543 , 0.93004628])

In [56]:
a2.min(axis=0)

array([0.0202184 , 0.04043679, 0.06065519, 0.08087359, 0.10109199])

In [61]:
a5 = np.random.normal(0,1,(100,5))
a5.shape

(100, 5)

In [62]:
a5.mean(axis=0)

array([-0.07271607, -0.17837509,  0.00832367, -0.08173388,  0.00830538])

In [63]:
a5.mean(axis=1)

array([ 0.3835206 ,  0.08107537, -0.23820199,  0.7521679 ,  0.34210952,
       -0.41403917, -0.17193642, -0.52299173, -0.37823284,  0.13853756,
        0.14520607,  0.17248319, -0.49188373,  0.0116472 ,  0.19097146,
        0.19814695,  0.51026438,  0.59316247,  0.24986204, -0.16904396,
       -0.17872055,  1.04301037, -0.66721455,  0.19207304, -0.36405662,
        0.51859969, -0.26874386,  0.50240549,  0.85928003, -0.87021659,
       -0.33687839, -0.28653485,  0.06700472,  0.26175892,  0.08156695,
       -1.31494588,  0.14315737, -0.41108489, -0.33279697, -0.40886095,
        0.05441296,  0.20291789,  0.47646166, -0.56174592, -0.32411879,
       -0.13347887, -0.33978084, -0.04805136, -0.31533384,  0.2222016 ,
       -0.246102  , -0.75084616, -0.12649455,  0.6507652 ,  0.15292565,
        0.38570275,  0.25349723,  0.22615299,  0.6313353 , -0.22916892,
       -0.44015075, -0.89615229, -0.58774274,  0.01245938, -0.26178942,
        0.21327791, -0.48473164, -0.05270161, -0.14141927, -0.47

In [64]:
np.argmin(a5)

217

In [68]:
a6 = np.array([11,12,13,14,15])
a6 < 13

array([ True,  True, False, False, False])

In [69]:
#Fancy Indexing
a7 = np.array([10, 11, 12, 13, 14,15,16,17,18,19,20])
a7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
#Fancy Indexing
a7_ind = np.array([[4,6], [3,5]])

print(a7[a7_ind])

[[14 16]
 [13 15]]


In [74]:
a8 = np.array([['a', 'b', 'c', 'd'], ['e','f','g','h'], ['i','j','k','l']])
a8

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l']], dtype='<U1')

In [75]:
print(a8[2,[2,0]])

['k' 'i']


In [76]:
print(a8[1:, [2,0]])

[['g' 'e']
 ['k' 'i']]


In [77]:
#
# **************PANDAS***************
#
import pandas as pd


In [78]:
print(pd.__version__)

1.2.4


In [79]:
#Series
s1 = pd.Series([0, 30, 60, 90, 120, 150,180])
s1

0      0
1     30
2     60
3     90
4    120
5    150
6    180
dtype: int64

In [80]:
type(s1)

pandas.core.series.Series

In [82]:
s11 = pd.Series([0, 30, 60, 90, 'angle 120', 'angle 150','angle 180'])
s11

0            0
1           30
2           60
3           90
4    angle 120
5    angle 150
6    angle 180
dtype: object

In [83]:
s1[3]

90

In [84]:
s11[5]

'angle 150'

In [85]:
s1.index

RangeIndex(start=0, stop=7, step=1)

In [86]:
s11.values

array([0, 30, 60, 90, 'angle 120', 'angle 150', 'angle 180'], dtype=object)

In [88]:
s1[:3]

0     0
1    30
2    60
dtype: int64

In [89]:
s1[4:]

4    120
5    150
6    180
dtype: int64

In [91]:
s1 = pd.Series([0, 30, 60, 90, 120, 150,180], index = ['a','b','c','d','e','f','g'])
s1

a      0
b     30
c     60
d     90
e    120
f    150
g    180
dtype: int64

In [92]:
#DataFrame
medianAge = pd.Series([46,42,47,45],index=['Germany','France','Italy','Spain'])
print(medianAge)

Germany    46
France     42
Italy      47
Spain      45
dtype: int64


In [94]:
df1 = pd.DataFrame(medianAge, columns=['Median Age'])
df1

Median Age
Germany          46
France           42
Italy            47
Spain            45

In [95]:
data = [{'V':i, 'V2':i**2} for i in range(5)]
print(data)

[{'V': 0, 'V2': 0}, {'V': 1, 'V2': 1}, {'V': 2, 'V2': 4}, {'V': 3, 'V2': 9}, {'V': 4, 'V2': 16}]


In [96]:
df2 = pd.DataFrame(data)
df2

V  V2
0  0   0
1  1   1
2  2   4
3  3   9
4  4  16

In [97]:
population = pd.Series([84,65,60,47], index=['Germany','France','Italy','Spain'])

In [99]:
df3 = pd.DataFrame({'population':population, 'medianAge':medianAge})
df3

population  medianAge
Germany          84         46
France           65         42
Italy            60         47
Spain            47         45

In [100]:
t1 = np.random.rand(3,2)
t1

array([[0.34471813, 0.71376687],
       [0.6391869 , 0.39916115],
       [0.43176013, 0.6145277 ]])

In [102]:
df4 = pd.DataFrame(t1,columns=['C1','C2'], index=['a','b','c'])
df4

C1        C2
a  0.344718  0.713767
b  0.639187  0.399161
c  0.431760  0.614528

In [104]:
df5 = pd.DataFrame(t1, index=['a','b','c'])
df5

0         1
a  0.344718  0.713767
b  0.639187  0.399161
c  0.431760  0.614528

In [105]:
df6 = pd.DataFrame(t1)
df6

0         1
0  0.344718  0.713767
1  0.639187  0.399161
2  0.431760  0.614528