In [67]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
from scipy.special import expit
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression

In [2]:
# Read in the file, “bank churn dataset.csv”, and create a dataframe.
df = pd.read_csv('bank churn dataset.csv')

In [3]:
# Follow the Column Key table for guidance on features and target.
df.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'TotalBalance',
       'NumOfProducts', 'HasCreditCard', 'IsActiveCustomer', 'Salary',
       'Exited'],
      dtype='object')

In [4]:
# For categorical data, remember to map to an integer. Hint: create a dictionary for gender values.
gender_code = {'Female':1,'Male':0}
df['Gender'] = df['Gender'].map(gender_code)

In [5]:
df = df.dropna(axis=0)

In [6]:
len(df)

10000

In [7]:
X = df.drop(labels=['Exited'], axis=1)

In [8]:
y = df['Exited']

In [9]:
# Normalize the features using MinMaxScaler.
mns = MinMaxScaler()

In [10]:
df_norm = mns.fit_transform(X)
df_norm

array([[0.538     , 1.        , 0.32432432, ..., 1.        , 1.        ,
        0.50673489],
       [0.516     , 1.        , 0.31081081, ..., 0.        , 1.        ,
        0.56270874],
       [0.304     , 1.        , 0.32432432, ..., 1.        , 0.        ,
        0.56965435],
       ...,
       [0.718     , 1.        , 0.24324324, ..., 0.        , 1.        ,
        0.21039009],
       [0.844     , 0.        , 0.32432432, ..., 1.        , 0.        ,
        0.46442905],
       [0.884     , 1.        , 0.13513514, ..., 1.        , 0.        ,
        0.19091423]])

In [15]:
len(df_norm)

10000

In [11]:
# Need to split the data into training set and test set. 
# Hint: use train_test_split with test_size of .3 and random_state=10.
X_train, X_test, y_train, y_test = train_test_split(df_norm, y, test_size=0.33, random_state=10)

In [12]:
# How many samples are you using for training and for testing?
X_train.size

60300

In [14]:
X_test.size

29700

In [18]:
# Create the model object using MLPRegressor. 
# Hint: start with hidden_layer_sizes=(9,2), solver = ‘lbfgs’, max_iter=10000, random_state=1
model = MLPRegressor(hidden_layer_sizes=(9,2), solver = 'lbfgs', max_iter=10000, random_state=1)

In [19]:
# Fit the model.
model.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(9, 2), max_iter=10000, random_state=1,
             solver='lbfgs')

In [20]:
# Make predictions using the test dataset.
y_pred = model.predict(X_test)
y_pred

array([0.37807563, 0.45820172, 0.67598159, ..., 0.12310452, 0.03858746,
       0.42519507])

In [21]:
# Compute the score using the X_test and y_test arguments.
score = model.score(X_test, y_test)
score

0.3210954213087235

In [54]:
# What do you conclude? The model may not make predictions with a high score. 
# Make a suggestion for a different modeling strategy.
# I changed values in the layers and interations and could not get a score better than .321...
model2 = MLPRegressor(hidden_layer_sizes=(7,2), solver = 'lbfgs', max_iter=1000000, random_state=1)

In [55]:
model2.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(9, 2), max_iter=1000000, random_state=1,
             solver='lbfgs')

In [56]:
y_pred2 = model2.predict(X_test)
y_pred2

array([0.37807563, 0.45820172, 0.67598159, ..., 0.12310452, 0.03858746,
       0.42519507])

In [57]:
score2 = model2.score(X_test, y_test)
score2

0.3210954213087235

In [58]:
#Testing using a LogisticRegression Model
# Used the test set with a Logistic Regression model and achieved a score of .7978... 
# It appears a neural network model is not best suited for this dataset.

lrm = linear_model.LogisticRegression(max_iter=5000)
lrm

LogisticRegression(max_iter=5000)

In [59]:
lrm.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [60]:
predictions = lrm.predict(X_test)
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [63]:
results = X_test
results

array([[1.        , 1.        , 0.35135135, ..., 0.        , 1.        ,
        0.8555048 ],
       [0.778     , 1.        , 0.2972973 , ..., 1.        , 0.        ,
        0.83517441],
       [0.678     , 1.        , 0.36486486, ..., 1.        , 0.        ,
        0.98905655],
       ...,
       [0.654     , 1.        , 0.31081081, ..., 1.        , 1.        ,
        0.0209233 ],
       [0.544     , 1.        , 0.22972973, ..., 1.        , 0.        ,
        0.2555305 ],
       [0.476     , 1.        , 0.32432432, ..., 1.        , 0.        ,
        0.2424562 ]])

In [65]:
score3 = lrm.score(X_test, y_test)
score3

0.7978787878787879

In [68]:
# Test/Train using Linear Regression Model
# Score is .12 so worse than a Neural Network model and not suitable for the dataset
model3 = LinearRegression(fit_intercept = True)

In [70]:
model3.fit(X_train, y_train)

LinearRegression()

In [71]:
y_predict3 = model3.predict(X_test)
y_predict3

array([0.26782085, 0.27692819, 0.3877788 , ..., 0.24135733, 0.21760893,
       0.42384629])

In [72]:
score4 = model3.score(X_test, y_test)
score4

0.12629771670821643