In [1]:
import numpy as np

In [2]:
# Print the version of numpy loaded in your environment
np.__version__

'1.20.1'

In [3]:
# Create a vector (one dimensional array) of sequential numbers from 0 to 25
np.arange(0, 26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [4]:
# Create 5 linear spaced numbers from 0 to 25
np.linspace(0, 25, 5)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [5]:
# Briefly describe an identity matrix and create a 6x6 identity array

# Identity matrix is a square array with 1's on the main diagonal
# Useful in linear algebra similiar to the number 1 in multiplication of real numbers
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
# Create a 6x6 array of random numbers between 0 and 10; this is step 5
a = np.random.randint(0, 10, (6,6))
print(a)

[[3 3 6 3 0 1]
 [4 0 1 8 6 0]
 [6 8 1 2 9 6]
 [4 6 5 4 3 4]
 [8 3 8 8 3 9]
 [8 4 5 4 1 3]]


In [26]:
# Using the 6x6 array from step 5, scale the numbers so that they are between 0 and 1
np.interp(a, (a.min(), a.max()), (0, 1))

array([[0.33333333, 0.33333333, 0.66666667, 0.33333333, 0.        ,
        0.11111111],
       [0.44444444, 0.        , 0.11111111, 0.88888889, 0.66666667,
        0.        ],
       [0.66666667, 0.88888889, 0.11111111, 0.22222222, 1.        ,
        0.66666667],
       [0.44444444, 0.66666667, 0.55555556, 0.44444444, 0.33333333,
        0.44444444],
       [0.88888889, 0.33333333, 0.88888889, 0.88888889, 0.33333333,
        1.        ],
       [0.88888889, 0.44444444, 0.55555556, 0.44444444, 0.11111111,
        0.33333333]])

In [24]:
# Using the 6x6 array from step 5, let’s examine the following attributes: 
# number of dimensions, shape, size, data type and the item size. 
# Add a comment with the item size in bytes.
print('Shape of Array from 5:',b.shape)
print('Size of Array from 5:',b.size)
print('Type of Array from 5:',b.dtype)
print('Item size of Array from 5:', b.itemsize, 'bytes')

Shape of Array from 5: (6, 6)
Size of Array from 5: 36
Type of Array from 5: int32
Item size of Array from 5: 4 bytes


In [30]:
# Using the 6x6 array from step 5, get the first 2 rows
print(a[:2])

[[3 3 6 3 0 1]
 [4 0 1 8 6 0]]


In [33]:
# Using the 6x6 array from step 5, get the second column
print(a[:,1:2])

[[3]
 [0]
 [8]
 [6]
 [3]
 [4]]


In [34]:
# Using the 6x6 array from step 5, create a 3 by 3 subarray from the top left corner; step 10
b = a[:3, :3]
b

array([[3, 3, 6],
       [4, 0, 1],
       [6, 8, 1]])

In [35]:
# Using the 3 by 3 subarray from step 10, double all of its values
c = b * 2
c

array([[ 6,  6, 12],
       [ 8,  0,  2],
       [12, 16,  2]])

In [36]:
# Using the 3 by 3 subarray from step 10, add 10 to all of its values
d = b + 10
d

array([[13, 13, 16],
       [14, 10, 11],
       [16, 18, 11]])

In [58]:
# Create two new vectors (one dimensional array) of sequential numbers from 0 to 25 and 25 to 50 
z = np.arange(1, 26)
y = np.arange(26, 51)
print(z,'\n',y)

# then resize them so that they are both 5x5 matrices
w = z.reshape((5,5))
x = y.reshape((5,5))
print('\n', w, '\n\n', x)

# and add them together to create a new square matrix; step 13
v = np.concatenate([w, x])
print('\n', v)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] 
 [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

 [[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [62]:
# Using the square matrices from step 13, create a new matrix by concatenating them by rows i.e. axis = 0; step 14
m = np.concatenate([w, x], axis=1)
m

array([[ 1,  2,  3,  4,  5, 26, 27, 28, 29, 30],
       [ 6,  7,  8,  9, 10, 31, 32, 33, 34, 35],
       [11, 12, 13, 14, 15, 36, 37, 38, 39, 40],
       [16, 17, 18, 19, 20, 41, 42, 43, 44, 45],
       [21, 22, 23, 24, 25, 46, 47, 48, 49, 50]])

In [67]:
# Using the matrix from step 14, find the total value
np.sum(m)

1275

In [71]:
# Using the matrix from step 14, find the mean of each row
np.mean(m, axis=1)

array([15.5, 20.5, 25.5, 30.5, 35.5])

In [72]:
# Using the matrix from step 14, find the mean of each column
np.mean(m, axis=0)

array([11., 12., 13., 14., 15., 36., 37., 38., 39., 40.])