In [ ]:
# dataset = []

# inputFile6 = open('.\\Desktop\\Florida Tech\\Python\\Sample210916.csv')

# for row in inputFile6 :
    

In [9]:
import csv
with open('c:\\users\\mfouq\\Desktop\\Florida Tech\\Python\\Sample210916.csv', 'r') as inputFile7 :
    csvReader = csv.reader(inputFile7)
    next(csvReader)
    dataset = []
    for row in csvReader :
        #casts data to a float
        row = [float(x) for x in row]
        dataset.append(row)

In [10]:
dataset

[[0.0, 0.0, 0.0, 0.0, 1.0, 0.073527031, 1.055074735],
 [1.0, 30.0, 0.523598776, 0.5, 0.866025404, 0.507838782, 0.882984485],
 [2.0, 60.0, 1.047197551, 0.866025404, 0.5, 0.894272373, 0.539692423],
 [3.0, 90.0, 1.570796327, 1.0, 6.12574e-17, 1.09107224, 0.021881489],
 [4.0, 120.0, 2.094395102, 0.866025404, -0.5, 0.96341565, -0.417546953],
 [5.0, 150.0, 2.617993878, 0.5, -0.866025404, 0.513761303, -0.797967449],
 [6.0, 180.0, 3.141592654, 1.22515e-16, -1.0, 0.083882328, -0.98548816],
 [7.0, 210.0, 3.665191429, -0.5, -0.866025404, -0.497426998, -0.810710334],
 [8.0, 240.0, 4.188790205, -0.866025404, -0.5, -0.809080363, -0.405999366],
 [9.0, 270.0, 4.71238898, -1.0, -1.83772e-16, -0.906891887, 0.010138536],
 [10.0, 300.0, 5.235987756, -0.866025404, 0.5, -0.773332379, 0.54559935],
 [11.0, 330.0, 5.759586532, -0.5, 0.866025404, -0.446607593, 0.919200078],
 [12.0, 360.0, 6.283185307, -2.4503e-16, 1.0, 0.059472315, 1.001977138]]

In [12]:
i = 2
dataset[i][6] - dataset[i-1][6]

-0.34329206200000006

In [13]:
#Writing a file
import csv
with open('c:\\users\\mfouq\\Desktop\\Florida Tech\\Python\\datasetClass.csv', 'w', newline='\n') as outputFile1 :
    listWriter = csv.writer(outputFile1, delimiter=',')
    for row in dataset :
        listWriter.writerow(row)
        

In [30]:
import csv
with open('c:\\users\\mfouq\\Desktop\\Florida Tech\\Python\\Global_Trends-1.csv', 'r') as hmwkData :
    csvReader = csv.reader(hmwkData)
    next(csvReader)
    hmwkDataset = []
    for row in csvReader :
        [hmwkDataset.append(row[0]), hmwkDataset.append(row[-1])]

In [31]:
hmwkDataset

['1961',
 '0.730353096',
 '1962',
 '0.74966053',
 '1963',
 '0.779376772',
 '1964',
 '0.807760435',
 '1965',
 '0.835587995',
 '1966',
 '0.862977419',
 '1967',
 '0.882514626',
 '1968',
 '0.913465004',
 '1969',
 '0.952250111',
 '1970',
 '1.004718665',
 '1971',
 '1.031077062',
 '1972',
 '1.063346182',
 '1973',
 '1.108474598',
 '1974',
 '1.103229535',
 '1975',
 '1.094765195',
 '1976',
 '1.140175644',
 '1977',
 '1.161759187',
 '1978',
 '1.176646346',
 '1979',
 '1.210336497',
 '1980',
 '1.187677817',
 '1981',
 '1.161137268',
 '1982',
 '1.145598408',
 '1983',
 '1.148379806',
 '1984',
 '1.176556388',
 '1985',
 '1.187730295',
 '1986',
 '1.20676859',
 '1987',
 '1.236179638',
 '1988',
 '1.271756266',
 '1989',
 '1.287914199',
 '1990',
 '1.290685385',
 '1991',
 '1.295408268',
 '1992',
 '1.285153254',
 '1993',
 '1.2866749',
 '1994',
 '1.29540036',
 '1995',
 '1.324253696',
 '1996',
 '1.335966819',
 '1997',
 '1.350979504',
 '1998',
 '1.348991702',
 '1999',
 '1.34950701',
 '2000',
 '1.379418921',
 '2001

In [32]:
#NUMPY

import numpy as np



In [35]:
A = np.zeros(10, dtype=int)

In [36]:
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
len(A)

10

In [38]:
type(A)

numpy.ndarray

In [41]:
B = np.ones((3,5), dtype=float)

In [42]:
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
P = np.full((4,4), 3.14)

In [44]:
P

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [47]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
#linear spacing
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [51]:
np.random.random((4,5))

array([[0.24746277, 0.90983251, 0.83844367, 0.23256884, 0.2460497 ],
       [0.79613439, 0.09238574, 0.82146326, 0.46555266, 0.53559304],
       [0.5854557 , 0.77504506, 0.02822044, 0.87047688, 0.96281709],
       [0.14692914, 0.88042132, 0.59988514, 0.07105183, 0.2392043 ]])

In [52]:
np.random.normal(0,1,(3,6))

array([[ 0.82640052, -1.30383738,  0.3925125 ,  0.69096833, -0.43142465,
        -1.18433962],
       [ 0.55918041,  0.44543553, -1.48949038,  1.00508555, -0.56164341,
         1.01707306],
       [-1.17239907,  1.64601057, -0.58076794, -0.40768089,  0.83094053,
         0.53364537]])

In [61]:
np.random.randint(0,10,(5,5))

array([[5, 5, 8, 7, 4],
       [5, 9, 6, 1, 6],
       [2, 5, 6, 6, 0],
       [6, 2, 7, 4, 3],
       [3, 1, 8, 1, 5]])

In [54]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [65]:
a1 = np.zeros(10, dtype='int16')

In [67]:
type(a1[1])

numpy.int16

In [68]:
a2 = np.random.normal(0,1,(3,6))

In [69]:
a2

array([[-0.10287106,  0.10281296, -0.16802469, -0.85605611,  0.05058388,
        -0.43338776],
       [ 0.2254107 , -0.36122872,  0.10551674,  0.08620687,  1.89263114,
         1.33405462],
       [ 1.05733942,  0.87577147, -0.29557621,  0.56821481,  0.69319473,
        -0.05634403]])

In [70]:
a2.ndim

2

In [71]:
a2.shape

(3, 6)

In [74]:
rand = np.random.RandomState(42)

In [77]:
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [78]:
y = rand.randint(100, size=10)
print(y)

[87 99 23  2 21 52  1 87 29 37]


In [79]:
print(x, y)

[51 92 14 71 60 20 82 86 74 74] [87 99 23  2 21 52  1 87 29 37]
